import logging
# logging : the process of recording events messages or data
# generated by a system, application or divice while it is running

# log level, format, handler

print("print vs logging")
print("Application Started .....")
print("Some thing went wrong ....")
print("Lets Log this ....")

logging.basicConfig(

    level=logging.DEBUG,

    format = "%(asctime)s | %(levelname)-8s | %(message)s",

    datefmt = "%H:%M:%S"
)

logging.debug("This is a DEBUG Message")
logging.info("This is INFO Message")
logging.warning("This is a Warning Message")
logging.error("This is a Error Message")
logging.critical("This is a Critical Message")